### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by jakub300** [vuejs/vue-template-explorer#1]
Sorry for the title but it simply doesn't work, errors as of now:
![image](https://user-images.githubusercontent.com/610941/50240402-ff1bdc00-03c4-11e9-980d-39d1ea160e71.png)

**Comment by yyx990803** [comment]
Looks like the root cause is unpkg's file resolution somehow broke: https://github.com/unpkg/unpkg.com/issues/156

Fixed in d4bd3bf453172cd0894b47dfa8fb785298d16256 with a workaround

**Comment by jakub300** [comment]
👍 Thanks for quick reaction and resolution
